# Generated by Django 2.0.4 on 2018-05-15 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='finproduit',
            name='finqte',
        ),
        migrations.AddField(
            model_name='finproduit',
            name='quantite',
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name='Quantite',
        ),
    ]
