# Generated by Django 2.0.4 on 2018-05-16 20:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0002_auto_20180515_2109'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarteBancaire',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('numero', models.IntegerField()),
                ('date', models.IntegerField()),
                ('code', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='client',
            old_name='nom',
            new_name='nom_complet',
        ),
        migrations.AlterField(
            model_name='finproduit',
            name='finopt',
            field=models.ManyToManyField(blank=True, to='mainapp.Option'),
        ),
    ]
