# Generated by Django 2.1.1 on 2018-09-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_auto_20180516_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='adresse',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='client',
            name='code_postal',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom_complet',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='client',
            name='tel',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='client',
            name='ville',
            field=models.CharField(max_length=5),
        ),
    ]
